services:
  app:
    build: .
    container_name: intelligent-job-matching
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: jobmatch_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: jobmatch
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

