"""Add is_read to ApplicationMessage

Revision ID: 2c855d21a166
Revises: 1413f542257a
Create Date: 2026-06-09 22:40:52.335290
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c855d21a166'
down_revision: Union[str, Sequence[str], None] = '1413f542257a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('application_messages', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_messages', 'is_read')
    # ### end Alembic commands ###
