"""Add interview model

Revision ID: 362fec24a84a
Revises: 96edfa71d3be
Create Date: 2026-06-09 21:18:10.256877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362fec24a84a'
down_revision: Union[str, Sequence[str], None] = '96edfa71d3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
