"""add_hidden_jobs

Revision ID: 636fafe750c1
Revises: 2c855d21a166
Create Date: 2026-06-13 23:18:33.021764
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636fafe750c1'
down_revision: Union[str, Sequence[str], None] = '2c855d21a166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
