"""add_external_link_to_job

Revision ID: 96edfa71d3be
Revises: c0664ab7cc92
Create Date: 2026-06-04 22:23:07.408480
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96edfa71d3be'
down_revision: Union[str, Sequence[str], None] = 'c0664ab7cc92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_link', sa.String(length=500), nullable=True))
    op.execute("UPDATE jobs SET external_link = ''")
    op.alter_column('jobs', 'external_link', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'external_link')
    # ### end Alembic commands ###
