"""sync_schema

Revision ID: c0664ab7cc92
Revises: 0002_add_audit_logs
Create Date: 2026-05-31 21:00:04.351643
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0664ab7cc92'
down_revision: Union[str, Sequence[str], None] = '0002_add_audit_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('birth_date', sa.String(length=20), nullable=False))
    op.add_column('candidate_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=False))
    op.add_column('candidate_profiles', sa.Column('cover_url', sa.String(length=500), nullable=False))
    op.add_column('candidate_profiles', sa.Column('bio', sa.Text(), nullable=False))
    op.add_column('candidate_profiles', sa.Column('education', sa.JSON(), nullable=False))
    op.add_column('candidate_profiles', sa.Column('experiences', sa.JSON(), nullable=False))
    op.alter_column('candidate_profiles', 'skills',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using="skills::json")
    op.add_column('jobs', sa.Column('brief_description', sa.Text(), nullable=False))
    op.add_column('jobs', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('jobs', 'required_skills',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using="required_skills::json")
    op.add_column('recruiter_profiles', sa.Column('company_website', sa.String(length=255), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('company_phone', sa.String(length=30), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('company_fax', sa.String(length=30), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('cover_url', sa.String(length=500), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('bio', sa.Text(), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('company_address', sa.String(length=500), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('overview', sa.JSON(), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('tax_id', sa.String(length=100), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('business_license_path', sa.String(length=500), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('verification_status', sa.String(length=30), nullable=False))
    op.add_column('recruiter_profiles', sa.Column('verification_note', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'phone')
    op.drop_column('recruiter_profiles', 'verification_note')
    op.drop_column('recruiter_profiles', 'verification_status')
    op.drop_column('recruiter_profiles', 'business_license_path')
    op.drop_column('recruiter_profiles', 'tax_id')
    op.drop_column('recruiter_profiles', 'overview')
    op.drop_column('recruiter_profiles', 'company_address')
    op.drop_column('recruiter_profiles', 'bio')
    op.drop_column('recruiter_profiles', 'cover_url')
    op.drop_column('recruiter_profiles', 'avatar_url')
    op.drop_column('recruiter_profiles', 'company_fax')
    op.drop_column('recruiter_profiles', 'company_phone')
    op.drop_column('recruiter_profiles', 'company_website')
    op.alter_column('jobs', 'required_skills',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using="required_skills::text")
    op.drop_column('jobs', 'end_date')
    op.drop_column('jobs', 'start_date')
    op.drop_column('jobs', 'brief_description')
    op.alter_column('candidate_profiles', 'skills',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using="skills::text")
    op.drop_column('candidate_profiles', 'experiences')
    op.drop_column('candidate_profiles', 'education')
    op.drop_column('candidate_profiles', 'bio')
    op.drop_column('candidate_profiles', 'cover_url')
    op.drop_column('candidate_profiles', 'avatar_url')
    op.drop_column('candidate_profiles', 'birth_date')
    # ### end Alembic commands ###
