"""add_preference_fields

Revision ID: c426a2d2bbf6
Revises: 636fafe750c1
Create Date: 2026-06-13 23:43:24.197107
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c426a2d2bbf6'
down_revision: Union[str, Sequence[str], None] = '636fafe750c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('preferred_domains', sa.Text(), server_default='', nullable=False))
    op.add_column('candidate_profiles', sa.Column('preferred_work_modes', sa.Text(), server_default='', nullable=False))
    op.add_column('candidate_profiles', sa.Column('preferred_employment_types', sa.Text(), server_default='', nullable=False))
    op.add_column('jobs', sa.Column('domain', sa.String(length=100), server_default='', nullable=False))
    op.add_column('jobs', sa.Column('work_mode', sa.String(length=50), server_default='On-site', nullable=False))
    op.add_column('jobs', sa.Column('employment_type', sa.String(length=50), server_default='Full-time', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'work_mode')
    op.drop_column('jobs', 'domain')
    op.drop_column('candidate_profiles', 'preferred_employment_types')
    op.drop_column('candidate_profiles', 'preferred_work_modes')
    op.drop_column('candidate_profiles', 'preferred_domains')
    # ### end Alembic commands ###
